let obj={
    data: [{
      name:'首页',
      key:'0',
      path:'/admin/home'
    },
    {
      name:'商品管理',
      key:'1',
      path:'/admin/food',
      children:[
        {
          name:'商品列表',
          path:'/admin/goods/list',
          key:'1-0'
        },
        {
          name:'商品添加',
          path:'/admin/goods/add',
          key:'1-1'
        }
        
      ]
    },
    {
        name:'banner管理',
        key:'3',
        path:'/admin/banner',
        children:[

          {
            name:'banner列表',
            path:'/admin/banner/list',
            key:'3-0'
          },
          {
            name:'banner添加',
            path:'/admin/banner/add',
            key:'3-1'
          },
          {
            name:'banner修改',
            path:'/admin/banner/update',
            key:'3-2'
          },
          {
            name:'banner删除',
            path:'/admin/banner/delete',
            key:'3-3'
          },

          
        ]
      },
      {
        name:'购物车管理',
        key:'4',
        path:'/admin/carts'
      },
      {
        name:'用户管理',
        key:'5',
        path:'/admin/home',
        children:[
          {
            name:'用户列表',
            path:'/admin/user/list',
            key:'5-0'
          },
          {
            name:'用户添加',
            path:'/admin/user/add',
            key:'5-1'
          },
          {
            name:'用户查询',
            path:'/admin/user/find',
            key:'5-2'
          }
        ]
      },
    ]
  }
  export default obj